ARG UBUNTU_RELEASE=26.04
FROM ubuntu:$UBUNTU_RELEASE AS builder

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        ca-certificates \
        build-essential pkgconf libssl-dev make clang lld \
        rust-1.93-all cargo rustc rust-clippy rustfmt rust-miri rust-1.93-src rust-1.93-doc \
        vim git curl just bacon xh hx \
        hyperfine ripgrep cargo-auditable cargo-mutants cargo-outdated \
        bash fish \
        autopkgtest dh-make dh-cargo git-buildpackage sbuild ubuntu-dev-tools devscripts \
    && cargo install --locked --root /usr cargo-audit cargo-deny cargo-vet cargo-vendor-filterer \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

USER root

EXPOSE 8000 8080

ENTRYPOINT [ "/usr/bin/fish" ]
